### PR TITLE
Added Static Analysis Tool: Plato

### PR DESCRIPTION
**Pull request by alicekang1**
_I will preface and say this was not on the 313 Starter List of Static and Dynamic tools, but it was listed on the Other Resources link. I checked with Prof Milton and he said this was okay for having "at least one tool that is not from our starter list"._

NOTE: The only test our implementation fails to pass are the lint tests. The TAs mentioned that if we were implementing a different static analysis tool, this is what should be happening (the TAs said it would be okay without the green check mark in this scenario).

Plato is a static analysis tool used to visualize code complexity.

**Concrete evidence that you had successfully installed the tool:**
- Added plato-report/ to repository
- plato-report/... includes many new files, one being index.html. This file will let you view on a browser the complexity of your code in a readable and interactive UI format.

**Concrete evidence that you had successfully installed the tool:**
- Provided are screenshots of the index.html file that monitor NodeBB:

Screenshot 2024-10-24 at 11 16 11 AM
Screenshot 2024-10-24 at 11 16 31 AM
Screenshot 2024-10-24 at 11 17 00 AM

### CODE REVIEW

**Review by JasmineRocket — COMMENTED** [review]
Solid evidence of tool installation by concrete amount of files added to the codebase, tests are working well and tools are functioning properly. Looks good to me!

**Review by JasmineRocket — APPROVED** [review]
Solid evidence of tool installation by concrete amount of files added to the codebase, tests are working well and tools are functioning properly. Looks good to me!

**Review by jullia02 — APPROVED** [review]
Successfully added tool reports and added tool to workflow for commits to the main branch, looks good to me!

**Comment by jullia02** [comment]
## Lint Test Failure Status Explanation

The default ESLint workflow check is failing because Plato's configuration does not align with the default ESLint rules. This is expected behavior as Plato has its own linting standards which we want to preserve for consistency. Moreover, changing Plato's code to match the ESLint rules could make future updates and maintenance more difficult. Our dedicated Plato integration workflow (`.github/workflows/plato.yml`) has passed successfully, confirming that our tool integration is working as intended.
Screenshot 2024-10-31 at 4 38 58 PM
Link: https://github.com/CMU-313/nodebb-f24-sweethearts/actions/runs/11616104264

**Pull request merged**
